### ISSUE TITLE
BUG1

### ISSUE THREAD

**Issue by liuben2008** [qindongliang/hbase-increment-index#1]
类：com.hbase.easy.index.HbaseSolrIndexCoprocesser

 for(String cf:column_family.split(",")) {//遍历所有的列簇
        	List<Cell> cells=put.getFamilyCellMap().get(Bytes.toBytes(cf));
              //先做判断，会报空指针
        	if(cells==null){
        		 //logger.info("cf="+cf+"取列簇cell列表为空..................");
        		 continue;
        	}
        	logger.info("cf="+cf);
            for (Cell kv :cells) {
                String name=Bytes.toString(CellUtil.cloneQualifier(kv));//获取列名
                String value=Bytes.toString(CellUtil.cloneValue(kv));//获取列值 or CellUtil.cloneValue(kv)  kv.getValueArray()
                logger.info("name="+name+"........value="+value);
                doc.addField(name,value);//添加到索引doc里面
            }
        }

**Comment by qindongliang** [comment]
感谢指出，已修复
